#!/usr/bin/env node

/**
 * Axiom Core Skills - Autonomous Evolution Telemetry Analyzer
 * 
 * Scans historical PROJECT_RETRO.md files generated by AI sessions 
 * to detect repeatedly failing rules and trigger auto-evolution.
 * 
 * Usage: npx ts-node product-core/scripts/telemetry-analyzer.ts <path-to-past-projects>
 */

import * as fs from 'fs';
import * as path from 'path';

console.log('🌌 [Autonomous Evolution Engine] Booting Telemetry Analyzer...');

const projectsDir = process.argv[2] || './past_projects';

if (!fs.existsSync(projectsDir)) {
    console.log(`ℹ️ No retro history found at ${projectsDir}. Skipping telemetry run.`);
    process.exit(0);
}

const findRetroFiles = (dir: string, fileList: string[] = []) => {
    fs.readdirSync(dir).forEach(file => {
        const filePath = path.join(dir, file);
        if (fs.statSync(filePath).isDirectory()) {
            findRetroFiles(filePath, fileList);
        } else if (file === 'PROJECT_RETRO.md') {
            fileList.push(filePath);
        }
    });
    return fileList;
};

const retroFiles = findRetroFiles(projectsDir);
if (retroFiles.length === 0) {
    console.log('ℹ️ No PROJECT_RETRO.md files found yet.');
    process.exit(0);
}

interface FailureLog {
    rule: string;
    count: number;
    projects: string[];
}

const failureData: Record<string, FailureLog> = {};

retroFiles.forEach(file => {
    const content = fs.readFileSync(file, 'utf8');
    const projectName = path.basename(path.dirname(file));
    
    // Naive parsing of Gate Metrics: FAIL sections
    const failMatches = content.matchAll(/FAIL:\s*(.*—)(—=\n|$)/gi);
    for (const match of failMatches) {
        const rule = match[1].trim();
        if (!failureData[rule]) {
            failureData[rule] = { rule, count: 0, projects: [] };
        }
        failureData[rule].count++;
        failureData[rule].projects.push(projectName);
    }
});

let evolutionTriggered = false;

console.log('\n📊 Telemetry Aggregation:');
Object.values(failureData).forEach(data => {
    console.log(`- Rule "${data.rule}" failed ${data.count} times. (${data.projects.join(', ')})`);
    if (data.count >= 5) {
        evolutionTriggered = true;
        console.log(`  🚨 EVOLUTION THRESHOLD REACHED (>5 failures).`);
        console.log(`  → Auto-Drafting \`skill-amendment-proposal.md\` for maintaining DDFM/ADBM structural resilience.`);
        // In a fully agentic flow, this would trigger a prompt sequence to rewrite the SKILL.md doc.
        fs.writeFileSync(
            path.join(process.cwd(), 'skill-amendment-proposal.md'), 
            `# 🧬 Autonomous Evolution Proposal\n\nRule \`${data.rule}\` has failed in ${data.count} projects.\n\n**Action Required**: Deep refactor of the underlying assumption in the Skill Package docs.`
        );
    }
});

if (!evolutionTriggered) {
    console.log('\n✅ Ecosystem Stable. No evolutionary pressure detected.');
}
