/** 
 * Axiom Core Telemetry Data Bridge
 * This file is automatically generated to sync Project Nexus state with the dashboard.
 */
window.AXIOM_DATA = {
  nexus: {
    "project_name": "Pet Official Website",
    "nexus_version": "2.0",
    "fspc_version": "9.6",
    "soul_scorecard": {
      "understanding": 9,
      "respect": 9,
      "companionship": 10,
      "delight": 9,
      "ethics": 10,
      "overall": 9.4
    },
    "global_compliance": {
      "tier": "Standard",
      "enforced_rules": ["WCAG 2.1 AA"]
    },
    "architecture_decisions": {
      "scale_tier": "Startup",
      "multi_tenancy": "N/A (B2C Landing)",
      "complexity_tier": "Monolith",
      "security_tier": "Standard"
    },
    "discovery_gates": {
      "gate_0a_prd": "passed",
      "gate_0b_arch": "passed",
      "gate_0c_scaffold": "pending"
    },
    "tech_stack": {
      "runtime": "Vite + React",
      "styling": "Vanilla CSS + OKLCH"
    }
  },
  soul: {
    "vision": "Create a digital sanctuary for pet owners that balances professional expertise with emotional warmth.",
    "core_principles": [
      "Emotional Connection First",
      "Clarity over Complexity",
      "Accessible Excellence",
      "Trustworthy Professionalism"
    ],
    "aesthetic_anchors": {
      "color_model": "OKLCH",
      "typography": "Rounded Sans-Serif",
      "motion": "Physics-based Spring",
      "layout": "Bento Grid / Airy Whitespace"
    }
  },
  last_sync: "2026-03-20T08:42:00Z"
};
